import { Container } from "@/src/components/layout/Container";
import { Card } from "@/src/components/ui/card";

const faqs = [
  {
    question:
      "How long does the assessment take?",
    answer:
      "Most organizations complete the assessment in under 3 minutes.",
  },
  {
    question:
      "Is the report generated by AI?",
    answer:
      "Yes. Each report includes an AI-generated executive summary, recommendations, and implementation roadmap tailored to your responses.",
  },
  {
    question:
      "Do I need technical knowledge?",
    answer:
      "No. The assessment is designed for business owners, managers, and decision-makers without requiring AI expertise.",
  },
  {
    question:
      "Can I retake the assessment?",
    answer:
      "Absolutely. You can submit multiple assessments to compare different business scenarios.",
  },
];

export function FAQ() {
  return (
    <section 
        id="faq"
        className="bg-muted/30 py-28">
      <Container>

        <div className="mx-auto mb-16 max-w-3xl text-center">

          <div className="inline-flex rounded-full bg-primary/10 px-4 py-2 text-sm font-semibold text-primary">
            FAQ
          </div>

          <h2 className="mt-4 text-4xl font-bold">
            Frequently Asked Questions
          </h2>

        </div>

        <div className="mx-auto max-w-4xl space-y-6">

          {faqs.map((faq) => (
            <Card
              key={faq.question}
              className="rounded-2xl p-8"
            >
              <h3 className="text-xl font-semibold">
                {faq.question}
              </h3>

              <p className="mt-4 leading-7 text-muted-foreground">
                {faq.answer}
              </p>
            </Card>
          ))}

        </div>

      </Container>
    </section>
  );
}